title:             Ladno Portfolio
email:             ladnopokaa@gmail.com
description:       Developer Portfolio.\nGames and Software.
author:            Jevgenij Ivanov
url:               "https://ladnopoka.github.io/"
baseurl:

# Social Profiles
twitter_username:  Ladnopokaa
github_username:   Ladnopoka

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
