title:             Ladno Developer Portfolio
email:             ladnopokaa@gmail.com
description:       Games and Software
author:            Jevgenij Ivanov
url:               "https://ladnopoka.github.io/"
baseurl: ""

# Social Profiles
twitter_username:  Ladnopokaa
github_username:   Ladnopoka
youtube_username:  \@LadnoDev
discord_username:  Ladno#3352 #https://discordapp.com/users/Ladno#3352
itch_username:     ladnogames
x_username:        Ladnopokaa

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
